name: VoKey
options:
  bundleIdPrefix: com.vokey
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  VoKey:
    type: application
    platform: macOS
    sources:
      - path: VoKey
        excludes:
          - "Resources/**"
      - path: VoKey/Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vokey.app
        INFOPLIST_FILE: VoKey/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: VoKey/SherpaOnnx/SherpaOnnx-Bridging-Header.h
        OTHER_LDFLAGS:
          - "-lc++"
          - "-L$(PROJECT_DIR)/Libraries"
          - "-lonnxruntime"
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/sherpa-onnx.xcframework/macos-arm64_x86_64/Headers"
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: "REDACTED_TEAM_ID"
        ENABLE_APP_SANDBOX: NO
        MACOSX_DEPLOYMENT_TARGET: "13.0"
    dependencies:
      - framework: Libraries/sherpa-onnx.xcframework
        embed: false
      - sdk: Accelerate.framework
      - sdk: Foundation.framework
      - sdk: AVFoundation.framework
      - sdk: libsqlite3.tbd

  VoKeyTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: VoKeyTests
    dependencies:
      - target: VoKey
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/VoKey.app/Contents/MacOS/VoKey"
        GENERATE_INFOPLIST_FILE: YES
