name: VowKy
options:
  bundleIdPrefix: com.vowky
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.8.0"

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  VowKy:
    type: application
    platform: macOS
    sources:
      - path: VowKy
        excludes:
          - "Resources/**"
      - path: VowKy/Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vowky.app
        INFOPLIST_FILE: VowKy/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: VowKy/SherpaOnnx/SherpaOnnx-Bridging-Header.h
        OTHER_LDFLAGS:
          - "-lc++"
          - "-L$(PROJECT_DIR)/Libraries"
          - "-lonnxruntime"
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/sherpa-onnx.xcframework/macos-arm64_x86_64/Headers"
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: ""  # Set your own Apple Developer Team ID
        ENABLE_APP_SANDBOX: NO
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: VowKy/VowKy.entitlements
        MACOSX_DEPLOYMENT_TARGET: "13.0"
    entitlements:
      path: VowKy/VowKy.entitlements
      properties:
        com.apple.security.cs.allow-unsigned-executable-memory: true
        com.apple.security.device.audio-input: true
    dependencies:
      - framework: Libraries/sherpa-onnx.xcframework
        embed: false
      - sdk: Accelerate.framework
      - sdk: Foundation.framework
      - sdk: AVFoundation.framework
      - sdk: libsqlite3.tbd
      - package: Sparkle

  VowKyTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: VowKyTests
    dependencies:
      - target: VowKy
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/VowKy.app/Contents/MacOS/VowKy"
        GENERATE_INFOPLIST_FILE: YES
